version: "3.8"

services:
  app1:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - REDIS_ADDR=redis:6379
  app2:
    build: ./product-service
    container_name: product-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres      
      - DB_NAME=mydb
      - REDIS_ADDR=redis:6379
  app3:
    build: ./order-service
    container_name: order-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - REDIS_ADDR=redis:6379
  app4:
    build: ./warehouse-service
    container_name: warehouse-service
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - REDIS_ADDR=redis:6379   
  app5:
    build: .
    container_name: shop-service
    ports:
      - "3004:3004"
    env_file:
      - .env    
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432    
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - REDIS_ADDR=redis:6379     
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  pgdata: 